services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # Path to frontend Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend  # Path to backend Dockerfile
      dockerfile: Dockerfile  # Path to backend Dockerfile
    env_file:
      .env
    ports:
      - "8000:8000"